# Configuration for probot-stale

daysUntilStale: 60      # Reduced from 90 since Keg is more agile
daysUntilClose: 7

exemptLabels:
  - "kind/feature"
  - "kind/bug"          # Added to keep important bugs tracked
  - "priority/high"     # Added for high priority items

exemptAssignees: true
staleLabel: stale

markComment: >
  This issue has been automatically marked as stale due to inactivity.
  It will be closed in 7 days if no further activity occurs.
  Thank you for your contributions to Keg!

limitPerRun: 10         # Reduced since Keg will have fewer issues

only: issues