#!/bin/sh

# Check if there are any Go files in the project
if [ -z "$(find . -name '*.go' -print -quit)" ]; then
  echo "No Go files to check. Skipping build and lint checks."
  exit 0
fi

echo "Checking if the code compiles..."
if ! go build ./...; then
  echo "Error: Code does not compile. Commit aborted."
  exit 1
fi

staged_go_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -z "$staged_go_files" ]; then
  echo "No Go files changed. Skipping golangci-lint."
  exit 0
fi

echo "Running govulncheck to check for vulnerabilities..."
if ! govulncheck ./...; then
  echo "Error: Vulnerabilities found. Commit aborted."
  exit 1
fi

echo "Running linters on Go files..."
if ! golangci-lint run --config .golangci.yml; then
  echo "Error: Linting issues detected."
  exit 1
fi